### PR TITLE
datasource/tls_certificate: Use local TLS server and certificate for verify failure testing

### LINKED ISSUE #516: datasource/tls_certificate: TestAccDataSourceCertificate_BadSSL test failures
### Terraform CLI and Provider Versions

N/A and `main`

### Terraform Configuration

```terraform
data "tls_certificate" "test" {
  url          = "https://untrusted-root.badssl.com/"
  verify_chain = false
}
```

### Expected Behavior

Acceptance test passes without modification over time.

### Actual Behavior

```
=== RUN   TestAccDataSourceCertificate_BadSSL
    data_source_certificate_test.go:166: Step 2/2 error: Check failed: Check 14/14 error: data.tls_certificate.test: Attribute 'certificates.1.sha1_fingerprint' expected "6922cd864f3c6299f6e751a019e5ddcdbc415a71", got "eede8b066561000952c3e599d4873eed75512a3b"
--- FAIL: TestAccDataSourceCertificate_BadSSL (0.64s)
```

### Steps to Reproduce

1. `terraform apply`

### How much impact is this issue causing?

Low

### Logs

_No response_

### Additional Information

The acceptance test already notes that this value is expected to change over time (presumably when the external SSL certificate is rotated).

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

### PR DESCRIPTION
**Pull request by bflad**
Closes #516

Previously (likely due to external SSL certificate rotation):

```
=== RUN   TestAccDataSourceCertificate_BadSSL
    data_source_certificate_test.go:166: Step 2/2 error: Check failed: Check 14/14 error: data.tls_certificate.test: Attribute 'certificates.1.sha1_fingerprint' expected "6922cd864f3c6299f6e751a019e5ddcdbc415a71", got "eede8b066561000952c3e599d4873eed75512a3b"
--- FAIL: TestAccDataSourceCertificate_BadSSL (0.64s)
```

The goal of this test is to ensure the data source returns an error if there is an invalid SSL certificate chain, which can be accomplished by running a local TLS server with expired or otherwise invalid SSL certificate.

There still is one external, real-world URL test with `TestAccDataSourceCertificate_TerraformIO`. It seems important to ensure there is one valid URL test for complete coverage though. If that test becomes a regular problem, a local TLS server could potentially be spun up with a valid SSL certificate via Let's Encrypt or something, however that effort is not being prioritized at the moment.

### CODE REVIEW

File: internal/provider/data_source_certificate_test.go [hunk 1]
```diff
@@ -163,46 +163,33 @@ func TestAccDataSourceCertificate_TerraformIO(t *testing.T) {
 // It can potentially break over time, and we will need to keep the
```
Comment (SBGoods) [inline internal/provider/data_source_certificate_test.go:163]: nit: Do we still need this note if we're no longer using a live certificate?

**Review by SBGoods — APPROVED** [review]

File: internal/provider/data_source_certificate_test.go (hunk 1 above)
Comment (bflad) [reply internal/provider/data_source_certificate_test.go:163]: Ha, nope, thank you will remove.
